id: hello_world_reporting_extension
name: Hello World reporting Extension
description: This is a hello world reporting extension
version: 1.0.0
authors: Ahmed Bargady <https://github.com/AhmedCoolProjects>
license: BSD

requirements: requirements.txt

channels:
  subscribe: [helloWorldInferenceExtensionChannel]

log:
  dir: ./logs
  level: DEBUG
